# Generated by Django 3.2.6 on 2024-12-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('correctiveaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_activity', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to='location.location')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HaccpAdminData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('used_for', models.CharField(max_length=200)),
                ('assign_task_to', models.CharField(max_length=200)),
                ('repeat_every', models.IntegerField()),
                ('repeat_frequency', models.CharField(max_length=200)),
                ('time_on', models.JSONField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('assign_verifiers', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrective_action', models.ManyToManyField(to='correctiveaction.CorrectiveAction')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('sub_storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='haccp.controlpoint')),
            ],
        ),
    ]
