# Generated by Django 3.2.6 on 2024-12-08 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correctiveaction', '0003_auto_20241208_1633'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0002_auto_20241208_1633'),
        ('haccp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haccpadmindata',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_haccp_admin_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='haccpadmindata',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_haccp_admin_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='haccpadmindata',
            name='sub_storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.controlpoint'),
        ),
        migrations.DeleteModel(
            name='ControlPoint',
        ),
    ]
