# Generated by Django 3.2.6 on 2024-12-14 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20241208_1633'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haccp', '0002_auto_20241208_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReHeatingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('sub_storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.controlpoint')),
            ],
        ),
        migrations.CreateModel(
            name='CoolingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_item', models.CharField(max_length=255)),
                ('internal_temp_at_0_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal_temp_at_1_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal_temp_at_2_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal_temp_at_3_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal_temp_at_4_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal_temp_at_5_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal_temp_at_6_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cooling_methods', models.CharField(blank=True, max_length=255, null=True)),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('text_message', models.TextField(blank=True, null=True)),
                ('supervisor_approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('supervisor_approved_status', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_approved_status', models.CharField(blank=True, max_length=200, null=True)),
                ('supervisor_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cooling_updates', to=settings.AUTH_USER_MODEL)),
                ('data_entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_cooling_data', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_cooling_updates', to=settings.AUTH_USER_MODEL)),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('sub_storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.controlpoint')),
            ],
        ),
        migrations.CreateModel(
            name='CookingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('sub_storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.controlpoint')),
            ],
        ),
    ]
