# Generated by Django 3.2.6 on 2024-12-15 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haccp', '0003_cookingdata_coolingdata_reheatingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingdata',
            name='corrective_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cooking_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='food_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='manager_approved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='manager_approved_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='meal_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_cooking_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='supervisor_approved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='supervisor_approved_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='supervisor_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='text_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookingdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reheating_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='date_of_reheating',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='food_item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='manager_approved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='manager_approved_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_reheating_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='reheating_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperature must be at least 75°C', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='supervisor_approved_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='supervisor_approved_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='supervisor_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='time_taken_for_reheating',
            field=models.DurationField(blank=True, help_text='Time must be less than 2 hours', null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='coolingdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coolingdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
