# Generated by Django 3.2.6 on 2025-01-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20241208_1633'),
        ('haccp', '0004_auto_20241215_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolingdata',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cooling_updates', to='authentication.userprofile'),
        ),
    ]
