# Generated by Django 3.2.6 on 2025-01-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20241208_1633'),
        ('haccp', '0005_alter_coolingdata_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolingdata',
            name='data_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_cooling_data', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='coolingdata',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_cooling_updates', to='authentication.userprofile'),
        ),
    ]
