# Generated by Django 3.2.6 on 2025-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0006_auto_20250109_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingdata',
            name='action_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coolingdata',
            name='action_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
