# Generated by Django 3.2.6 on 2025-01-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20241208_1633'),
        ('haccp', '0007_auto_20250112_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingdata',
            name='data_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_cooking_data', to='authentication.userprofile'),
        ),
    ]
