# Generated by Django 3.2.6 on 2025-01-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20241208_1633'),
        ('haccp', '0008_cookingdata_data_entered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reheatingdata',
            name='action_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='corrective_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reheatingdata',
            name='data_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_reheating_data', to='authentication.userprofile'),
        ),
    ]
