# Generated by Django 3.2.6 on 2025-01-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0009_auto_20250113_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reheatingdata',
            name='reheating_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reheatingdata',
            name='time_taken_for_reheating',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
