# Generated by Django 3.2.6 on 2024-12-08 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haccp', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature_value', models.FloatField()),
                ('haccp_link_time_given', models.TimeField(blank=True, null=True)),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('text_message', models.TextField(blank=True, null=True)),
                ('supervisor_approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('supervisor_approved_status', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_approved_status', models.CharField(blank=True, max_length=200, null=True)),
                ('supervisor_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_updates', to='authentication.userprofile')),
                ('haccp_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='haccp.haccpadmindata')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_daily_updates', to='authentication.userprofile')),
            ],
        ),
    ]
