# Generated by Django 5.1.3 on 2024-12-02 12:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_alter_userprofile_role'),
        ('correctiveaction', '0001_initial'),
        ('haccp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('text_message', models.TextField(blank=True, null=True)),
                ('supervisor_approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('supervisor_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('corrective_actions', models.ManyToManyField(blank=True, related_name='daily_updates', to='correctiveaction.correctiveaction')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_updates', to='authentication.userprofile')),
                ('haccp_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='haccp.haccpadmindata')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_daily_updates', to='authentication.userprofile')),
            ],
        ),
    ]
