# Generated by Django 5.1.3 on 2024-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyupdates',
            name='corrective_actions',
        ),
        migrations.AddField(
            model_name='dailyupdates',
            name='corrective_actions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
