# Generated by Django 5.1.3 on 2024-12-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_remove_dailyupdates_corrective_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdates',
            name='haccp_link_time_given',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
