# Generated by Django 3.2.6 on 2025-01-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20241208_1633'),
        ('usersapp', '0002_auto_20241208_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdates',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_updates', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='dailyupdates',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_daily_updates', to='authentication.userprofile'),
        ),
    ]
