# Generated by Django 5.1.3 on 2024-12-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_dailyupdates_haccp_link_time_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdates',
            name='manager_approved_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailyupdates',
            name='supervisor_approved_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
