# Generated by Django 3.2.6 on 2024-12-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_dailyupdates_manager_approved_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyupdates',
            old_name='max_value',
            new_name='temperature_value',
        ),
        migrations.RemoveField(
            model_name='dailyupdates',
            name='min_value',
        ),
    ]
