# Generated by Django 3.2.6 on 2024-12-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haccp', '0001_initial'),
        ('correctiveaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='control_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='haccp.controlpoint'),
        ),
    ]
