# Generated by Django 3.2.6 on 2024-12-08 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0002_auto_20241208_1633'),
        ('correctiveaction', '0002_correctiveaction_control_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_action_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_action_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='control_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='location.controlpoint'),
        ),
    ]
