# Generated by Django 3.2.6 on 2024-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiveaction', '0003_auto_20241208_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveaction',
            name='name',
            field=models.CharField(error_messages={'action': 'Action required'}, max_length=200),
        ),
    ]
