# Generated by Django 3.2.6 on 2024-12-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalhygiene', '0002_alter_personalhygiene_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalhygiene',
            name='employee_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalhygiene',
            name='inspector_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
