# Generated by Django 3.2.6 on 2024-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalhygiene', '0003_auto_20241206_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='photo',
            field=models.ImageField(upload_to='media/personal_hygiene_photos/'),
        ),
    ]
