# Generated by Django 5.1.3 on 2024-11-28 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('line_staff', 'Line Staff'), ('supervisors', 'Supervisors'), ('managers', 'Managers'), ('e_learning', 'e-Learning')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('employee_id', models.IntegerField(unique=True)),
                ('data_of_joining', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
