# Generated by Django 4.2.16 on 2024-11-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
