# Generated by Django 4.2.16 on 2024-11-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('line_staff', 'Line Staff'), ('supervisors', 'Supervisors'), ('managers', 'Managers'), ('e_learning', 'e-Learning')], max_length=50),
        ),
    ]
