# Generated by Django 5.1.3 on 2024-11-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_data_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='data_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
