# Generated by Django 5.1.3 on 2024-12-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('line_staff', 'Line Staff'), ('supervisor', 'Supervisor'), ('managers', 'Managers'), ('e_learning', 'e-Learning')], max_length=50, null=True),
        ),
    ]
